### ISSUE TITLE
Try new BS4 Dashboard Theme for Validator

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#10]
Pretty cool new dashboard themer: https://rinterface.github.io/bs4Dash/index.html

Seems like a lot of nice functionality we could add without much headache if we go with a dashboard layout.

**Comment by wincowgerDEV** [comment]
@shelly-mippr Wondering if you would be interested in helping with this.

**Comment by shelly-mippr** [comment]
Yes. Let's talk about it when you get back from vacation.

**Comment by wincowgerDEV** [comment]
Done
