### ISSUE TITLE
[Feature]: Finalizing Data Portal

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#115]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

- [x] Metadata to add to the portal (if not already there): MRL and MDA (Medium priority)
- [x] Comparison between locations or groups of data in data visualizer. (Low priority) 
- [x] #117
- [x] Add metadata on how to prep blanks (think more about)
- [x] Add sampling metadata into the dataset (high priority)
- [x] Digestion and density separation information for methodology add to metadata (high priority)
- [x] Allow for downloading more than 1 dataset at a time. (medium priority)
- [x] Allow download all data at once (high priority)
- [x] People want to extract things out of the zip folder so potentially store unzipped. (high priority) 
- [x] #116
- [x] Adding some flexibility for how much spectra people share, potentially 10% or something similar. (high priority)
- [x] Create a gui for data download to help people filter. (low priority)
- [x] Have a way to check for duplicate entries without having to upload a previous certificate. (high priority)
- [x] Create a tier 2 website for sharing data from outside labs for any environmental microplastic (low priority)
- [x] Allow comments at each level in the dataset (high priority)
- [x] Add anonymous comment box in the tool that people can submit info through, could also implement a request key (low priority)
- [x] Download spreadsheets from the data analysis portal (medium priority)

### Problem

NA

### Proposed Solution

NA

### Alternatives Considered

NA

**Comment by hsherrod2019** [comment]
'Allow comments at each level in the dataset (high priority)'- modified in One4All portal

**Comment by hsherrod2019** [comment]
Btw, modifications to validator tool (or anything related to that tool, ex. rules sheet) should be made in the One4All portal rather than here:)

**Comment by hsherrod2019** [comment]
"Want security to hide certain information, want to hide machine that they use to measure the data with, lab name and contact information, could poach clients, they could check boxes to request that some data is not shared. (follow up with elap, high priority)"

Check SDWIS to see if any information needs to be hidden

**Comment by wincowgerDEV** [comment]
Putting the unzipped data for this issue may be challenging "People want to extract things out of the zip folder so potentially store unzipped. (high priority)", unsure how to structure the information online. Also unsure if this would cause some corruption issues.

**Comment by wincowgerDEV** [comment]
Completed all to the best of our ability.
