### ISSUE TITLE
Integrate NCEI Data Schema with ours

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#13]
NCEI is creating a comprehensive data portal for microplastics on the ocean's surface: https://experience.arcgis.com/experience/b296879cc1984fda833a8acc93e31476/page/Page/?data_id=dataSource_1-181deb0dbd3-layer-1%3A480&views=Map-Viewer

We should try to bridge our schema with theirs so that we can also host their data and vice versa.

**Comment by hannahhapich** [comment]
This looks dope! I also like the idea of having some sort of notation for what constitutes very low, low, moderate, high, and very high concentrations. I would imagine that number is different for drinking water than ocean water, so we'll maybe have to do some digging around in the literature if there isn't already a guideline for that. Or maybe we could just make those recommendations based off of the data we collected. As far as the other components go included in their schema, I think all we're missing is the organization, key words, a long written version of the citation as a separate column, and noting some kind of region/subregion of the world. Let me know if any or all of those categories sound interesting to you and I'll get working on them.

**Comment by wincowgerDEV** [comment]
Thanks @hannahhapich I think the Organization and Region/Subregion could be useful to add, what do you think?

**Comment by hannahhapich** [comment]
Sounds good. On it!
