### ISSUE TITLE
Thinking about the "Best" Microplastic Taxonomy

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#14]
Hey @hannahhapich 

Thinking about this after reviewing the link to merge with the wikidata terms https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/blob/481af068fa27dee9798bdf3b78c0d1940f83e1bf/data/Microplastics_DataPortal_Clean_Morphology.xlsx

I wonder if we should focus the microplastic taxonomy on individual terms i.e. no "Films/fragments" Since really all that is saying is "Films; Fragments" in our current schema. Maybe we could model any dual terms like that in our schema that way we won't need to make a wikidata item for every combination of categories we just link our schema to the two wikidata entries for Films and Fragments. Does that make sense?

**Comment by wincowgerDEV** [comment]
I wonder if we could use this logic to consolidate the Trash Taxonomy 2.0 too?

**Comment by wincowgerDEV** [comment]
One other point here, I think we should keep the categories in the database for each study as reported by the study and then use the microplastic taxonomy in the database to transform the data. i.e. if a study reports "fibres" leave it like that and then if we need to make a summary report we use the morphology taxonomy relational table to transform it to "fiber".

**Comment by hannahhapich** [comment]
Hey Win, yes I agree going forward the recommendation should be not to combine categories. I believe we already incorporated this in our last update and also in Wikidata!
