### ISSUE TITLE
Modularize the applications

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#17]
I was thinking through the long term strategy for all of these applications. They are all pretty general purpose and could and should be used for other projects. I think we might want to consider making a separate R package that allows people to deploy the apps as functions and modularize aspects they may want to change, for example the microplastic image explorer will likely need to live in the data portal but also a separate version for the research community who wants a ton of different images that are not from the accredited labs. I could see it going a lot of ways. Also the image explorer is probably general purpose for uses outside of microplastics, same with the validation app. We had to build them from the ground up because nothing like this existed. Modularizing them could have wide spanning utility. 

I think the best milestones for modularization might entail these steps:
- [ ]  Create a function that defines the UI and one for the server. 
- [ ] Place that function in a separate code. 
- [x] Use the bs4dash throughout all apps so that they can be quickly nested if for example you wanted to have sidebar item for each app. 
- [ ] We could make each function refer to a separate bs4dash sidebar item. Nest the about and other info as dropdown sidebar options for each application component. 
- [ ] Consider what people want modularized. e.g. in the image explorer they probably want the default google sheet and the dropdown sorting options. 
- [ ] It may even be ideal to create separate packages for each app then an all encompassing package for the microplastics data portal for example.

**Comment by wincowgerDEV** [comment]
We could make each app a lot like the CA.gov web frameworks but for data portals.

**Comment by wincowgerDEV** [comment]
https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/commit/b2a101db16a53dcf975b07659785e88dcf2bd2e5 added support for config files to support the main aspects I think people would want to implement.

**Comment by LibbyHeeren** [comment]
It might be worthwhile to investigate shiny frameworks like golem (which forces you to create a package), and rhino (which doesn't force you to create a package).

**Comment by wincowgerDEV** [comment]
This is some great advice. Reading into them a little looks like both do pretty similar things so just need to figure out which will be the better framework for this. I am kind of leaning towards building a package with golem currently because it looks like rhino requires the modules which sounds challenging to maintain but I will give both a deep dive. Both seem pretty well supported.

**Comment by wincowgerDEV** [comment]
Closing, no longer the intended usecase
