### ISSUE TITLE
Data Upload Errors

### ISSUE THREAD

**Issue by hannahhapich** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#23]
Column names cannot contain any numeric values anywhere in the titles, and data upload occasionally results in a disconnection from the server.

**Comment by hannahhapich** [comment]
Hey Win,

Sure, here's the rules file that is showing the error for the numbers. I was using the complete rules with all column names but cut it down to just the first set and the only attribute column rule that was showing the error help me troubleshoot.
[Validation_Rules_Samples_Merged copy 2.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10026374/Validation_Rules_Samples_Merged.copy.2.csv)

And here's the rules file and data file that cause the server disconnect.
[Validation_Rules_Samples_Merged copy.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10026372/Validation_Rules_Samples_Merged.copy.csv)

[Samples_Merged copy.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10026369/Samples_Merged.copy.csv)

**Comment by wincowgerDEV** [comment]
Thanks Hannah! Will test these out soon.

**Comment by wincowgerDEV** [comment]
The first rule in question was this: 

```r
Size_3000um <=1|Size_3000um%vin%c(â€œN/Aâ€) |Size_3000um%vin%c(â€œPresentâ€)
```
- Note their are some strange characters here, perhaps from an incorrect UTF type conversion? 


If I update it to this I avoid the error:
```r
Size_3000um <=1|Size_3000um%vin%c("A")
```
- I don't think the numbers in the column names is the problem, I think it is the unique characters. Will investigate further what to do about that. For now will just let people know characters need to be in the english alphabet.

**Comment by wincowgerDEV** [comment]
Second issue is returning this error:
"Warning: Error in <Anonymous>: unable to find an inherited method for function ‘variables’ for signature ‘"notSubsettableError"’
  1: shiny::runApp"
- Investigating.

**Comment by wincowgerDEV** [comment]
Looks like some of the characters are throwing an error that isn't being caught by the current tests
![image](https://user-images.githubusercontent.com/26821843/203821855-c71cfaaf-2f3c-48a2-9abd-340d92e494b6.png)

**Comment by wincowgerDEV** [comment]
updated the rules catching and now we get a nice error that I think is a little easier to understand for the second issue. 
![image](https://user-images.githubusercontent.com/26821843/203823289-8caeb9f4-3e70-4bf5-a0a2-d1bd980b3d95.png)

**Comment by wincowgerDEV** [comment]
I think these statements are problematic because they mix logic for numeric formatted data and character formatted data, it can't be both simultaneously.

"Material_PE_PS <= 1|Material_PE_PS%vin%c("N/A") | Material_PE_PS%vin%("Present")"

We could instead do something like this as long as we set the default format to character for all of them. 
"as.numeric(Material_PE_PS) <= 1|Material_PE_PS%vin%c("N/A") | Material_PE_PS%vin%("Present")"

**Comment by wincowgerDEV** [comment]
I think the validation package does not allow for some special characters in the names and/or in the rules. Found some rows that had ";" and others with "-" and others with "+" in either the name of the variable or the name of the rule. I could imagine that the function will complain because those characters also could be interpreted as part of the rule. For example, if the rule says Material+PA == 3, is that referring to a column named Material+PA or is that referring to a request to add the Material column to the PA column and make sure they equal 3? We should create a list of these and check for them and provide an error or warning that makes sense if someone is using one of those.

**Comment by wincowgerDEV** [comment]
Should probably make a call that loops through all the rules rows one at a time and sees if the function complains and then return those rows back to the user so that they know what rules are likely problematic.

**Comment by wincowgerDEV** [comment]
Return a df of the complaints per row.

**Comment by wincowgerDEV** [comment]
This one is a real conundrum. 

If I run these datasets in the only tool (and now on the desktop version too) the app says that the rules were successful, but if I run the raw functions in global.R then there is an error. We need some expert help. @shelly-mippr Have you ever seen a case where a function on a server operates differently from a function living offline? I think it could be something having to do with the csv file when it is being read into the server it reads fine but when it is on my desktop it reads incorrectly? Not super sure, if you or @hannahhapich have some ideas they would be much appreciated. 

[Validation_Rules_Samples_Merged.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10127149/Validation_Rules_Samples_Merged.csv)

[Samples_Merged.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10127148/Samples_Merged.csv)

**Comment by wincowgerDEV** [comment]
> This one is a real conundrum.
> 
> If I run these datasets in the only tool (and now on the desktop version too) the app says that the rules were successful, but if I run the raw functions in global.R then there is an error. We need some expert help. @shelly-mippr Have you ever seen a case where a function on a server operates differently from a function living offline? I think it could be something having to do with the csv file when it is being read into the server it reads fine but when it is on my desktop it reads incorrectly? Not super sure, if you or @hannahhapich have some ideas they would be much appreciated.
> 
> [Validation_Rules_Samples_Merged.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10127149/Validation_Rules_Samples_Merged.csv)
> 
> [Samples_Merged.csv](https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/files/10127148/Samples_Merged.csv)

Don't know what happened but this is fixed now.

**Comment by wincowgerDEV** [comment]
Closing this issue now. I think we have caught the problematic errors well enough to at least give people somewhere to go next without it crashing.
