### ISSUE TITLE
[Feature]: Add test for duplicated data

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#33]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Someone may resubmit the same thing to CKAN. We need a way to make sure the records are unique. 

### Problem

Someone might submit data to CKAN multiple times, we don't want that to be double counted. 

### Proposed Solution

Check that dataset keys don't exist on CKAN already. 

### Alternatives Considered

Run analysis on the backend to just look at the most recent data uploaded if there are duplicates.

**Comment by wincowgerDEV** [comment]
IS this something we can do on the back end?

**Comment by wincowgerDEV** [comment]
Seems very related to https://github.com/Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal/issues/36

If you allow for submission of duplicate data then you are just prescribe a mandate that says that the most recent data submitted is accepted as the record and all others are previous versions.

**Comment by hannahhapich** [comment]
Yeah, this seems to be resolved by #36 to me.
