### ISSUE TITLE
[Feature]: Gemma comments on data analysis portal and image explorer

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#46]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Comments for improving the data analysis portal and image explorer from Gemma. 

### Problem

User friendliness of portal. 

### Proposed Solution

Microplastic Image Explorer
https://wincowger.shinyapps.io/microplastic_image_explorer/
General
- [x] combine about text and image matrix (about text is sparse and images are compelling) 
- [x] about text as collapsable section (default open)
- [x] move contribute to left sidebar as static link

Filters
- [x] Consider making filter lists dynamic so that you don’t end up with empty queries
- [x] Add a “clear all” button that clears the current filter selection
- [x] Create a breadcrumb in the header area the indicates what filters are represented by the filtered image matrix (so that you don’t have to visually traverse the filters)
- [x] Indicate when a filter is selected with a slight change in style like a different color border

Display
- [x] Make all image display boxes the same size

- [x] Standardize the size of the expanded images and be sure they are centered
- [x] Paginate after a certain number of images (60?) or allow the user to choose how to view

Microplastic Data Analysis
https://wincowger.shinyapps.io/data_analysis/
General 
- [x] Combine overview text and map (don’t bury the lede by having the map a click away unless you’re planning on adding a lot more content to the landing page)
- [x] Remove collapsible container for map
- [x] Add a legend that is by default open
- [x] Can you clarify what data you are symbolizing the points with?
- [x] Reconsider the application name - seems more like display than analysis.
- [x] How do you deal with multiple samples at the same lat/long? Can you provide an example?
- [x] Limit how far you can zoom out (no repeating geography)
- [x] Add the word “concentration” to the tool tip so that the user knows what they are looking at

**Comment by wincowgerDEV** [comment]
Change ‘success’ button to ‘download certificate’

**Comment by wincowgerDEV** [comment]
- [ ] Put all data outside repo. 
- [ ] Make relative paths to files and code. 
- [ ]Create an R package for things. 
- [ ] Share a cleaned up version of the config file. 
- [ ] Create tests for the shiny app. 
	- [ ] Use selenium for front end automated testing. The application in itself is kind of already a test. 
	- [ ] Lorenzo may have made used modules for the components of the R Shiny. 
- [ ] The testing across the databases?
	- [ ] What is the analogous query for each one and then see if we can get the expected result from all?
	- [ ] Create a unique ID for the images. Create a directory with that id and pop the image inside of it. Add that to the path with what we are displaying. Check to make sure the image is the right file type. No executable files. What are the executable file types to worry about? Make sure that the files.  Maybe an R library to test if the file is a safe file. 
	- [ ] Geo black light open source community they are working together a lot. They have a slack channel that a lot of people are working. Maybe make a microplastic coding community slack. 
	- [ ] Set default page as the introduction for doing the data analysis. 
	- [ ] Make sure that the boxes are the same size. Ok if images are not the same size. 
	- [ ] Leaflet with R might have more control than the mapviewer. 
	- [ ] Get state and county boudaries for the us, then do a spatial analysis to figure out. 
	- [ ] Maybe aggregate everything to the country level since that is the scale that we are currently certain about. 
	- [ ] Different tabs for different spatial resolution, California only or world wide at the country level.

**Comment by wincowgerDEV** [comment]
Hey @hsherrod2019, can you help with these for the data analysis portal?

Microplastic Data Analysis
https://wincowger.shinyapps.io/data_analysis/
General

 - [ ] Combine overview text and map (don’t bury the lede by having the map a click away unless you’re planning on adding a lot more content to the landing page)
 - [ ] Remove collapsible container for map
 - [ ] Add a legend that is by default open
 - [ ] Can you clarify what data you are symbolizing the points with?
 - [ ] Reconsider the application name - seems more like display than analysis.
 - [ ] How do you deal with multiple samples at the same lat/long? Can you provide an example?
 - [ ] Limit how far you can zoom out (no repeating geography)
 - [ ] Add the word “concentration” to the tool tip so that the user knows what they are looking at
 - [ ] Set default page as the introduction for doing the data analysis. 
 - [ ] Leaflet with R might have more control than the mapviewer.
 - [ ] Get state and county boudaries for the us, then do a spatial analysis to figure out.
 - [ ] Maybe aggregate everything to the country level since that is the scale that we are currently certain about.
 - [ ] Different tabs for different spatial resolution, California only or world wide at the country level.

**Comment by hsherrod2019** [comment]
'Get state and county boundaries for the us, then do a spatial analysis to figure out.' 

Not going to do this one yet because we don't have enough data for the state and county boundaries for the US.

**Comment by wincowgerDEV** [comment]
> Change ‘success’ button to ‘download certificate’, add a description about the need to download.

Done

**Comment by wincowgerDEV** [comment]
Moving these to a new issue because I feel they are part of longer term development. There is quite a bit of automated and manual testing baked into a shiny app and the automated testing is really specific but we want to stay general purpose for now. 

 Create tests for the shiny app.
 Use selenium for front end automated testing. The application in itself is kind of already a test.
 Lorenzo may have made used modules for the components of the R Shiny.

**Comment by wincowgerDEV** [comment]
finished.
