### ISSUE TITLE
[Feature]: Get state and county boundaries for the us, then do a spatial analysis to figure out.

### ISSUE THREAD

**Issue by hsherrod2019** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#49]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Part of the previous comments for improving the data analysis portal and image explorer.

### Problem

Creating a spatial analysis based on state and county boundaries for the US.

### Proposed Solution

- [ ] Gather data for state and county boundaries for the US
- [ ] Create a spatial analysis map based on that data

### Alternatives Considered

Other ways to scale the data?

**Comment by wincowgerDEV** [comment]
This is no longer needed.
