### ISSUE TITLE
[Bug]: Lat Longs Incorrect Windows Poorly handles UTF8 characters. 

### ISSUE THREAD

**Issue by wincowgerDEV** [Moore-Institute-4-Plastic-Pollution-Res/Microplastic_Data_Portal#50]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

Current

### What happened?

There are incorrect lat long coordinates in the online dataset for drinking water microplastics: https://data.ca.gov/dataset/microplastics-in-drinking-water/resource/b027a5ef-d42e-415c-b9b9-257c1bd5ae89

Currently unable to update them correctly because UTF-8 Errors on Windows. 

### Steps to reproduce

Read the linked dataset on a Windows machine. 

### Expected behavior

Correct lat longs

### Additional Information

Suggest Using the code below to update the dataset lat longs.  

```r
library(tidyverse)
library(readxl)
library(tidygeocoder)
library(sf)  
library(mapview)
library(mapdata)
library(data.table)

# Read Samples Excel file into R
# Data file does not exist
Samples_excel <- fread("https://data.ca.gov/dataset/e7624fce-c058-4fa1-a29f-2594d8f8f160/resource/b027a5ef-d42e-415c-b9b9-257c1bd5ae89/download/samples_merged.csv", encoding = "UTF-8")

# Geocode locations to closest precision possible, add XY location values
Samples_GeoCoded <- Samples_excel %>%
  geocode("Location", method = 'osm', lat = "Approximate_Latitude", long = "Approximate_Longitude")

```

**Comment by wincowgerDEV** [comment]
@hsherrod2019, did this get finished?

**Comment by hsherrod2019** [comment]
@wincowgerDEV 
Yes, everything is up to date with the lat longs! There are a few cells that have multiple locations per cell (as we talked about earlier), so those are the only ones that could not be corrected, but I made a note in the app indicating that.
